### ISSUE TITLE
Sketch block accessibility improvements

### ISSUE THREAD

**Issue by oskosk** [Automattic/block-experiments#217]
* [x] Add an example preview [Addressed by #218]
* [x] Allow for an alt / title tag. [Addressed by #227] Release as version 1.0.9
* [x] Add role="img" [Addressed by #227] Release as version 1.0.9

**Comment by skorasaurus** [comment]
re: accessibility, check out https://www.deque.com/blog/creating-accessible-svgs/

**Comment by oskosk** [comment]
Thanks @skorasaurus
